spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 924974325932-vidksk9nslq2qusvn7pt8abff3hdjvcg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/career
    username: root
    password: lyi98549854
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
server:
  port: 8030
